base_url = "https://atalazer.github.io"
title = "Atalazer's Blogs"

# v1 Tail
theme = "v1"

taxonomies = [
    {name = "tags", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"
render_emoji = true
smart_punctuation = true

[extra]
author = "Atalazer"
author_url = "https://github.com/atalazer"
